# Generated by Django 5.1.6 on 2025-04-20 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_remove_product_images_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-amount', '-created_at']},
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='current_price',
            new_name='current_bid',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='winner',
            new_name='highest_bidder',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='start_price',
            new_name='starting_bid',
        ),
        migrations.AddField(
            model_name='auction',
            name='bid_increment',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='auction',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
